version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toto
  php:
    build: ./php-fpm
    volumes:
      - ./symfony:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
    environment:
      - SYMFONY__SESSION__SECRET
    links:
      - db
  nginx:
    build: ./nginx
    ports:
      - "8003:80"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
