version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    build: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ./symfony:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
    environment:
      - SYMFONY__SESSION__SECRET
    links:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
